### ISSUE TITLE
找不到 config.example.js

### ISSUE THREAD

**Issue by Wanye-7300** [genuine-oj/frontend-naive#1]
我在看语雀的教程，在 https://www.yuque.com/yxzl/genuine-oj/frontend 中提到了 config.example.js 这个文件，但是我我在根目录下找不到，求问为什么

**Comment by yxzlwz** [comment]
https://www.yixiangzhilv.com/docs/genuine-oj/introduction.html

文档已经迁移至新站点，语雀忘记删除了，抱歉给您造成困扰

为了方便在前端界面中直接更改设置，现在我们已将配置文件移动到后端项目中，所以你无须再手动设置配置文件，首次访问项目时后端将自动完成
